sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    
    #安装任务一需要使用的工具imagemagick
    - sudo apt-get install imagemagick

script:
  - bash test.sh
  #任务一 用bash编写一个图片批处理脚本 测试用用例
  #- bash job4/img.sh -d job4/img -r 50%x50%
  ##支持对jpeg格式图片进行图片质量压缩
  - bash job4/img.sh -d job4/img -q 50 
  ##支持对jpeg/png/svg格式图片在保持原始宽高比的前提下压缩分辨
  - bash job4/img.sh -d job4/img -r 50%x50%
  ##支持对图片批量添加自定义文本水印
  - bash job4/img.sh -d job4/img -w "hello world"
  ##支持批量重命名（统一添加文件名前缀，不影响原始文件扩展名）
  - bash job4/img.sh -d job4/img --prefix "haha"
  ##支持将png/svg图片统一转换为jpg格式图片
  - bash job4/img.sh -d job4/img -c
  ##支持多参数混合使用，如将png/svg图片统一转换为jpg格式图片后添加水印
  - bash job4/img.sh -d job4/img -c -w  "hello world"
  

after_script:
  - /usr/bin/shellcheck test.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
